### ISSUE TITLE
Bugs!

### ISSUE THREAD

**Issue by karalets** [facebookresearch/Blackbox-Coresets-VI#1]
Gents,

I just tried to run this and we have some import bugs/installation bugs.
This is an error message I get after a clean installation following the instruction in our repo.
@dionman do you want to have a look?

$ python3 psvi/experiments/flow_psvi.py --datasets "halfmoon" "four_blobs" --architecture "fn" --n_hidden 100 --methods "psvi_learn_v" "mfvi_subset" --coreset_sizes 10 50 --init_at "subsample" --num_trials 3

Traceback (most recent call last):
  File "psvi/experiments/flow_psvi.py", line 20, in <module>
    from psvi.inference.baselines import (
  File "/Users/karaletsos/anaconda3/lib/python3.8/site-packages/psvi/inference/baselines.py", line 16, in <module>
    from psvi.models.logreg import model, laplace_precision, mcmc_sample, logreg_forward
  File "/Users/karaletsos/anaconda3/lib/python3.8/site-packages/psvi/models/logreg.py", line 8, in <module>
    import stan
ModuleNotFoundError: No module named 'stan'

**Comment by dionman** [comment]
Thanks!
Added pystan dependency on `setup.py`. This is required to execute some baseline methods on the logistic regression model using `mcmc_sampling` (not the default option at present)
