### ISSUE TITLE
more bugs

### ISSUE THREAD

**Issue by karalets** [facebookresearch/Blackbox-Coresets-VI#2]
as I keep executing our code, I also got this:

$ python3 psvi/experiments/flow_psvi.py --datasets "halfmoon" "four_blobs" --architecture "fn" --n_hidden 100 --methods "psvi_learn_v" "mfvi_subset" --coreset_sizes 10 50 --init_at "subsample" --num_trials 3
Traceback (most recent call last):
  File "psvi/experiments/flow_psvi.py", line 103, in <module>
    action=argparse.BooleanOptionalAction,
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

**Comment by dionman** [comment]
The package needs `python>=3.9`.
