### ISSUE TITLE
shifted halfmoon

### ISSUE THREAD

**Issue by karalets** [facebookresearch/Blackbox-Coresets-VI#3]
@dionman in our internal experiments, we had a very interesting shifted halfmoon logReg one.

At first glance I did not find it here, do you have instructions for how I can get that for me, please?

Many thanks

**Comment by dionman** [comment]
A linearly separable version of the halfmoon data can be produced for example replacing https://github.com/facebookresearch/Blackbox-Coresets-VI/blob/6d26fba6ff8ee55175938f1d5a6e5119bb7a33d7/psvi/experiments/experiments_utils.py#L684-L687 as follows:
```
(X, Y), num_classes = make_moons(n_samples=1000, noise=0.1, random_state=42), 2; X[Y==0, 1] += 1
```
